#!/bin/bash

icon_on=""
icon_off="󰂲"

status=$(rfkill list bluetooth | grep -i "Soft blocked: yes")

if [ "$BLOCK_BUTTON" = "1" ]; then
    if [ -n "$status" ]; then
        rfkill unblock bluetooth
    else
        rfkill block bluetooth
    fi
fi

if [ -n "$status" ]; then
    echo "$icon_off"
else
    echo "$icon_on"
fi